# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1octTxYw9uAfJHlxv6LSM3rKNxPirsSiE
"""

infosys_data = {
    'YEAR': [23, 22, 21, 20, 19, 18, 17, 16, 15],
    'DPR': [58.77, 59.8, 50.74, 61.46, 93.64, 46.42, 50.51, 43.88, 42.01],
    'ROC': [43.03, 38.46, 32.23, 31.28, 38.38, 31, 27.8, 20.75, 25.29],
    'ROE': [34.34, 30.63, 25.23, 24.97, 23.44, 25.44, 20.31, 20.78, 25.3]
}

import pandas as pd

infosys_df = pd.DataFrame(infosys_data)

wipro_df = pd.DataFrame(wipro_data)

hcl_data = {
    'YEAR': [23, 22, 21, 20, 19, 18, 17, 16, 15],
    'DPR': [113.4, 104.75, 37.25, 15.12, 13.42, 22.98, 49.26, 57.16, 37.59],
    'ROC': [34.76, 30.14, 27.76, 28.84, 32, 32.52, 31.49, 21.37, 31.86],
    'ROE': [27.87, 25.53, 20.07, 24.04, 26.88, 26.7, 26.46, 21.95, 32.7]
}

hcl_df = pd.DataFrame(hcl_data)

tech_mahindra_data = {
    'YEAR': [23, 22, 21, 20, 19, 18, 17, 16, 15],
    'DPR': [123.63, 88.79, 45.61, 60.69, 31.42, 25.9, 45.24, 36.09, 25.67],
    'ROC': [19.23, 22.37, 20.39, 21.93, 24.31, 22.85, 20.7, 21.04, 22.45],
    'ROE': [15.21, 19, 16.94, 20.35, 21.21, 20.46, 18.04, 23.75, 20.04]
}

tech_mahindra_df = pd.DataFrame(tech_mahindra_data)

# Merge dataframes on 'YEAR'
merged_df = pd.merge(infosys_df, wipro_df, on='YEAR', suffixes=('_infosys', '_wipro'))
merged_df = pd.merge(merged_df, hcl_df, on='YEAR', suffixes=('', '_hcl'))
merged_df = pd.merge(merged_df, tech_mahindra_df, on='YEAR', suffixes=('_hcl', '_tech_mahindra'))

# Select features and target for each company
features_infosys = merged_df[['DPR_infosys', 'ROC_infosys', 'ROE_infosys']]
target_infosys = merged_df['YEAR']

features_wipro = merged_df[['DPR_wipro', 'ROC_wipro', 'ROE_wipro']]
target_wipro = merged_df['YEAR']

features_hcl = merged_df[['DPR_hcl', 'ROC_hcl', 'ROE_hcl']]
target_hcl = merged_df['YEAR']

features_tech_mahindra = merged_df[['DPR_tech_mahindra', 'ROC_tech_mahindra', 'ROE_tech_mahindra']]
target_tech_mahindra = merged_df['YEAR']

from sklearn.linear_model import LinearRegression

# Initialize and fit linear regression models
reg_infosys = LinearRegression().fit(features_infosys, target_infosys)
reg_wipro   =   LinearRegression().fit(features_wipro, target_wipro)
reg_hcl     =     LinearRegression().fit(features_hcl, target_hcl)
reg_tech_mahindra = LinearRegression().fit(features_tech_mahindra, target_tech_mahindra)

# Predictions
pred_infosys = reg_infosys.predict(features_infosys)
pred_wipro = reg_wipro.predict(features_wipro)
pred_hcl = reg_hcl.predict(features_hcl)
pred_tech_mahindra = reg_tech_mahindra.predict(features_tech_mahindra)

# Print coefficients and intercepts
print("Infosys Coefficients:", reg_infosys.coef_)
print("Infosys Intercept:", reg_infosys.intercept_)

print("Wipro Coefficients:", reg_wipro.coef_)
print("Wipro Intercept:", reg_wipro.intercept_)

print("HCL Coefficients:", reg_hcl.coef_)
print("HCL Intercept:", reg_hcl.intercept_)

print("Tech Mahindra Coefficients:", reg_tech_mahindra.coef_)
print("Tech Mahindra Intercept:", reg_tech_mahindra.intercept_)

from sklearn.metrics import mean_squared_error, r2_score

import pip, sklearn

!pip install matplotlib

import matplotlib.pyplot as plt

# Evaluate the models
mse_infosys = mean_squared_error(target_infosys, pred_infosys)
r2_infosys = r2_score(target_infosys, pred_infosys)

mse_wipro = mean_squared_error(target_wipro, pred_wipro)
r2_wipro = r2_score(target_wipro, pred_wipro)

mse_hcl = mean_squared_error(target_hcl, pred_hcl)
r2_hcl = r2_score(target_hcl, pred_hcl)

mse_tech_mahindra = mean_squared_error(target_tech_mahindra, pred_tech_mahindra)
r2_tech_mahindra = r2_score(target_tech_mahindra, pred_tech_mahindra)

print("Infosys Mean Squared Error:", mse_infosys)
print("Infosys R-squared:", r2_infosys)

print("Wipro Mean Squared Error:", mse_wipro)
print("Wipro R-squared:", r2_wipro)

print("HCL Mean Squared Error:", mse_hcl)
print("HCL R-squared:", r2_hcl)

print("Tech Mahindra Mean Squared Error:", mse_tech_mahindra)
print("Tech Mahindra R-squared:", r2_tech_mahindra)

# Plotting the results
plt.figure(figsize=(12, 8))

plt.subplot(2, 2, 1)
plt.scatter(target_infosys, pred_infosys)
plt.title('Infosys Regression')

plt.subplot(2, 2, 2)
plt.scatter(target_wipro, pred_wipro)
plt.title('Wipro Regression')

plt.subplot(2, 2, 3)
plt.scatter(target_hcl, pred_hcl)
plt.title('HCL Regression')

plt.subplot(2, 2, 4)